// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AspIT_Voting.Web.Models
{
    public partial class Activity
    {
        public Activity()
        {
            UserActivities = new HashSet<UserActivity>();
        }

        public int ActivityId { get; set; }
        public string ActivityName { get; set; }
        public int VoteCount { get; set; }
        public DateTime CreationDate { get; set; }

        public virtual ICollection<UserActivity> UserActivities { get; set; }
    }
}