// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AspIT_Voting.Web.Models
{
    public partial class ActivitySuggestion
    {
        public int ActivitySuggestionId { get; set; }

        [Required(ErrorMessage = "Feltet skal udfyldes")]
        [Display(Name = "Aktivitet")]
        public string ActivitySuggestionName { get; set; }
    }
}