// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AspIT_Voting.Web.Models
{
    public partial class ActivitySuggestion
    {
        public int ActivitySuggestionId { get; set; }
        public string ActivtySuggestionName { get; set; }
    }
}