// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AspIT_Voting.Web.Models
{
    public partial class FoodSuggestion
    {
        public int FoodSuggestionId { get; set; }
        public string FoodSuggestionName { get; set; }
    }
}